
name: Trigger License Check

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  call-license-check:
    uses: brcm-test/.github/.github/workflows/license-check.yml@main
    with:
      pull-request-target: true
    secrets: inherit
