name: Trigger License Check

on:
  pull_request_target:
    types: [opened, synchronize, closed]
  issue_comment:
    types: [created]

jobs:
  call-license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event Payload
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event payload:"
          cat "$GITHUB_EVENT_PATH"

      - name: Invoke License Check Workflow
        uses: brcm-test/.github/.github/workflows/license-check.yml@main
        with:
          pull-request-target: true
          issue-comment: true
        secrets: inherit
